pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-pat',
                    url: 'https://github.com/<your-username>/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat """
                python -m venv .venv
                call .\\.venv\\Scripts\\activate
                python -m pip install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                pip3 install pytest
                """
            }
        }

        stage('Run Tests') {
            steps {
                bat """
                call .\\.venv\\Scripts\\activate
                pytest --junitxml=messaging_app/pytest-report.xml
                """
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: "messaging_app/pytest-report.xml"
                }
            }
        }
    }
}
